name: CI

on:
  workflow_dispatch: # Allow manual runs.
  pull_request:
    branches: [ 'main' ]
  push:
    branches: [ 'main' ]

jobs:
  set-matrix:
    name: Set CI target to matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - uses: actions/checkout@v3
      - uses: bazelbuild/setup-bazelisk@v2
      - run: sudo apt update && sudo apt install -y jq
      - id: set-matrix
        run: echo matrix=$(bazel query 'attr("tags", "'amd64'", "//...")' | tr ':' '/' | awk -F '/' '{print $3}' | uniq | jq -Rc . | jq -cs .) >> $GITHUB_OUTPUT

  ci:
    needs: set-matrix
    strategy:
      matrix:
        target: ${{ fromJson(needs.set-matrix.outputs.matrix) }}
    name: CI for ${{ matrix.target }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: bazelbuild/setup-bazelisk@v2
    - name: Build and test
      run: |
        set -ex
        for i in $(seq 5); do bazel fetch --loading_phase_threads=1 //... && break || sleep 20; done
        bazel build --curses=no //...
        bazel test --curses=no --test_output=errors //...
        # Ignore experimental targets, which might not pass.
        # TODO: Fix or remove these exceptions.
        targets=$(bazel query 'attr("tags", "'amd64'", "//${{ matrix.target }}/...")')
        bazel build --curses=no ${targets}
        bazel test --curses=no --test_output=errors ${targets}
        
  ci-results:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Final Results
    needs: [ci]
    steps:
      - run: |
          result="${{ needs.build.result }}"
          if [[ $result == "success" || $result == "skipped" ]]; then
            exit 0
          else
            exit 1
          fi
